// The golden vectors are the cross-platform contract. The Python reference and
// the Swift, Kotlin and JavaScript ports all replay the same files; if any drifts,
// the model sees different features on that platform and the implementations
// disagree silently. This exists so drift fails loudly instead.
//
// Regenerate with `python scripts/gen_golden.py` in the training repo, in the same
// commit as any change to the normalizer, hasher or router spec.
import { test } from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

import { Tongue, normalize, route, fnv1a, buckets, MAX_CHARACTERS } from "../dist/index.js";

const here = dirname(fileURLToPath(import.meta.url));
const vectors = async (name) => JSON.parse(await readFile(join(here, name), "utf8"));

test("normalizer matches the reference", async () => {
  const { cases, max_chars } = await vectors("normalize_vectors.json");
  assert.ok(cases.length > 0, "no normalizer cases loaded");
  for (const { input, output } of cases) {
    assert.equal(normalize(input), output, `normalize(${JSON.stringify(input)})`);
  }
  // The cap counts code points, matching Python's slice.
  assert.equal(MAX_CHARACTERS, max_chars);
  const long = "é".repeat(max_chars + 50);
  assert.equal([...normalize(long)].length, max_chars, "code-point truncation");
});

test("hasher matches the reference", async () => {
  const v = await vectors("hashing_vectors.json");
  for (const { input, hash } of v.fnv1a) {
    assert.equal(fnv1a(input), hash, `fnv1a(${JSON.stringify(input)})`);
  }
  // Whole-bag equality: catches boundary marking, order coverage and the modulo,
  // which per-string hashes alone would not.
  for (const { normalized, bag } of v.bags) {
    const actual = buckets(normalized, v.num_buckets, v.ngram_orders);
    const expected = new Map(Object.entries(bag).map(([k, n]) => [Number(k), n]));
    assert.equal(actual.size, expected.size, `bag size for ${JSON.stringify(normalized)}`);
    for (const [bucket, count] of expected) {
      assert.equal(actual.get(bucket), count, `bucket ${bucket} of ${JSON.stringify(normalized)}`);
    }
  }
});

test("router matches the reference", async () => {
  const { cases } = await vectors("script_vectors.json");
  assert.ok(cases.length > 0, "no router cases loaded");
  for (const c of cases) {
    const normalized = normalize(c.input);
    assert.equal(normalized, c.normalized, `normalization before routing ${JSON.stringify(c.input)}`);
    const r = route(normalized);
    assert.equal(r.verdict, c.verdict, `verdict for ${JSON.stringify(c.input)}`);
    assert.deepEqual([...r.candidates], c.candidates, `candidates for ${JSON.stringify(c.input)}`);
    assert.equal(r.script, c.script ?? null, `script for ${JSON.stringify(c.input)}`);
  }
});

test("changing one narrowing route does not change later routes", () => {
  const text = "привет как твои дела";
  const expected = ["ru", "uk", "bg", "sr", "mk", "be", "kk", "ky"];
  const first = route(text);
  assert.deepEqual([...first.candidates], expected);

  first.candidates.length = 0;
  try {
    assert.deepEqual([...route(text).candidates], expected);
  } finally {
    first.candidates.push(...expected);
  }
});

test("detects across scripts", async () => {
  const tongue = await Tongue.load({ from: join(here, "..", "dist") });
  for (const [text, expected] of [
    ["je voudrais un café au lait", "fr"],
    ["kann ich das haben", "de"],
    ["muchas gracias por la ayuda", "es"],
    ["привет как твои дела", "ru"],
    ["안녕하세요 만나서 반갑습니다", "ko"],
    ["こんにちは、お元気ですか", "ja"],
    ["مرحبا كيف حالك اليوم", "ar"],
    ["ᏣᎳᎩ ᎦᏬᏂᎯᏍᏗ", "chr"],
    ["the garage sale is on saturday morning", "en"],
  ]) {
    assert.equal(tongue.detect(text).language, expected, `detect(${JSON.stringify(text)})`);
  }
});

test("says 'too close to call' rather than guessing", async () => {
  const tongue = await Tongue.load({ from: join(here, "..", "dist") });
  // Equally Italian and Spanish; presenting one would be a lie.
  assert.ok(tongue.detect("la casa").isTooCloseToCall);
  // Reads as Welsh to any character model. The point is that it says so.
  assert.equal(tongue.detect("hi i am").reliability, "tentative");
  assert.equal(tongue.detect("   ").reliability, "empty");
  assert.equal(tongue.detect("   ").language, null);
});

test("detection output matches the reference head", async () => {
  // The head had no vectors at all: nothing in any port asserted a probability,
  // which is how three ports came to disagree on `language` for hashtag input
  // while every suite stayed green. Generated by scripts/gen_detection_vectors.py,
  // a fourth implementation reading the shipped weights.
  const vectors = JSON.parse(await readFile(join(here, "detection_vectors.json"), "utf8"));
  const tongue = await Tongue.load({ from: join(here, "..", "dist") });
  for (const c of vectors.cases) {
    const d = tongue.detect(c.input);
    assert.equal(d.normalized, c.normalized, `${c.input}: normalized`);
    assert.equal(d.language, c.language, `${c.input}: language`);
    assert.equal(d.reliability, c.reliability, `${c.input}: reliability`);
    assert.equal(d.isTooCloseToCall, c.isTooCloseToCall, `${c.input}: isTooCloseToCall`);
    assert.equal(d.candidates.length, c.candidateLanguages.length, `${c.input}: candidate count`);
    c.candidateLanguages.forEach((language, i) => {
      assert.equal(d.candidates[i].language, language, `${c.input}: candidate ${i}`);
      const delta = Math.abs(d.candidates[i].probability - c.candidateProbabilities[i]);
      assert.ok(
        delta <= vectors.tolerance,
        `${c.input}: probability ${i} off by ${delta} (tolerance ${vectors.tolerance})`,
      );
    });
  }
});
